version: "3.8"

services:
  # Backend Service
  todoApp:
    image: wisekingdavid/todo-app:0.1
    container_name: todo-server
    ports:
      - "9500:9500"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/todo-postgres-db
      - SPRING_DATASOURCE_USERNAME=todo-postgres
      - SPRING_DATASOURCE_PASSWORD=todo-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SW_AGENT_NAME:todo-app
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES:host.docker.internal:11800
    networks:
      - backend
      # - frontend

  # Database
  PostgreSQL:
    image: postgres
    container_name: todo-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=todo-postgres
      - POSTGRES_PASSWORD=todo-postgres
      - POSTGRES_DB=todo-postgres-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  # Skywalking
  oap:
    image: apache/skywalking-oap-server:9.1.0
    container_name: oap

    restart: on-failure:5
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: ["CMD-SHELL", "/skywalking/bin/swctl ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SW_STORAGE: h2
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
    depends_on:
      - todoApp
    networks:
      - backend

  ui:
    image: apache/skywalking-ui:9.1.0
    container_name: ui
    links:
      - oap
    ports:
      - "8088:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800
    depends_on:
      - oap

networks:
  backend:
  frontend:
