FROM maven:3-openjdk-17-slim AS maven
WORKDIR /app
COPY pom.xml .
RUN #mvn -e -B dependency:resolve
COPY src ./src
RUN mvn clean package -DskipTests=true


FROM openjdk:17-jdk-alpine
COPY --from=maven /app/target/*.jar app.jar

ENV SW_AGENT_COLLECTOR_BACKEND_SERVICES="host.docker.internal:11800" \
    SW_AGENT_NAME="todo-server"

COPY skywalking-agent /usr/local/agent

EXPOSE 9500
ENTRYPOINT ["sh", "-c", "java -javaagent:/usr/local/agent/skywalking-agent.jar=agent.service_name=todo-server -jar app.jar"]